return {
	["date"]= 20130630,
	["keybinds"]= {
		{"togglecammode", "Ctrl+backspace"},
		{"togglecammode", "Shift+backspace"},
		{"edit_backspace", "Any+backspace"},
		{"toggleoverview", "None"},
		{"edit_complete", "Any+tab"},
		{
			"chatally", 			{"Alt+enter", "Alt+numpad_enter"},
		},
		{
			"chatswitchally", 			{"Alt+enter", "Alt+numpad_enter"},
		},
		{
			"chatall", 			{"Ctrl+enter", "Ctrl+numpad_enter"},
		},
		{
			"chatswitchall", 			{"Ctrl+enter", "Ctrl+numpad_enter"},
		},
		{"chatspec", "None"},
		{"chatswitchspec", "None"},
		{
			"chat", 			{"Any+enter", "Any+numpad_enter"},
		},
		{
			"edit_return", 			{"Any+enter", "Any+numpad_enter"},
		},
		{"pause", "pause"},
		{"crudemenu", "esc"},
		{"exitwindow", "shift+esc"},
		{"quitforce", "Ctrl+Shift+esc"},
		{"edit_escape", "Any+escape"},
		{"speedup", "None"},
		{"prevmenu", ","},
		{"decguiopacity", "Shift+,"},
		{"slowdown", "None"},
		{"nextmenu", "."},
		{"incguiopacity", "Shift+."},
		{"specteam 9", "0"},
		{"specteam 19", "Ctrl+0"},
		{"group0", "Any+0"},
		{"specteam 0", "1"},
		{"specteam 10", "Ctrl+1"},
		{"group1", "Any+1"},
		{"specteam 1", "2"},
		{"specteam 11", "Ctrl+2"},
		{"group2", "Any+2"},
		{"specteam 2", "3"},
		{"specteam 12", "Ctrl+3"},
		{"group3", "Any+3"},
		{"specteam 3", "4"},
		{"specteam 13", "Ctrl+4"},
		{"group4", "Any+4"},
		{"specteam 4", "5"},
		{"specteam 14", "Ctrl+5"},
		{"group5", "Any+5"},
		{"specteam 5", "6"},
		{"specteam 15", "Ctrl+6"},
		{"group6", "Any+6"},
		{"specteam 6", "7"},
		{"specteam 16", "Ctrl+7"},
		{"group7", "Any+7"},
		{"specteam 7", "8"},
		{"specteam 17", "Ctrl+8"},
		{"group8", "Any+8"},
		{"specteam 8", "9"},
		{"specteam 18", "Ctrl+9"},
		{"group9", "Any+9"},
		{
			"buildfacing inc", 			{"Any+insert", "[", "Shift+["},
		},
		{
			"drawinmap", 			{"Any+\\", "Any+`", "Any+0xa7", "Any+^"},
		},
		{"clearmapmarks", "Alt+`"},
		{"buildfacing dec", "Any+delete"},
		{"attack", "f"},
		{"movestate", "h"},
		{"firestate", "C+a"},
		{"areaattack", "Alt+a"},
		{"debug", "Ctrl+Alt+n"},
		{"debugcolvol", "Ctrl+Alt+b"},
		{"repeat", "f1"},
		{"priority", "None"},
		{"selfd", "delete"},
		{"selectcomm", "tab"},
		{"manualfire", "d"},
		{"airmanualfire", "d"},
		{"oneclickwep", "d"},
		{"placebeacon", "d"},
		{"selectmissiles", "Any+d"},
		{"reclaim", "e"},
		{"fight", "a"},
		{"forcestart", "Alt+f"},
		{"areaguard", "g"},
		{"gameinfo", "Ctrl+Alt+i"},
		{"wantcloak", "k"},
		{"togglelos", "None"},
		{"loadunits", "l"},
		{"loadselected", "l"},
		{"rawmove", "m"},
		{"singlestep", "Alt+o"},
		{"patrol", "p"},
		{"groupclear", "Shift+q"},
		{"repair", "r"},
		{"stop", "s"},
		{"stopproduction", "f2"},
		{"globalbuildcancel", "alt+s"},
		{"unloadunits", "u"},
		{"techup", "None"},
		{"pastetext", "Ctrl+v"},
		{"wait", "None"},
		{"areamex", "w"},
		{"areaterramex", "alt+w"},
		{"wantonoff", "o"},
		{"pushpull", "o"},
		{"buildspacing dec", "Any+x"},
		{"buildspacing inc", "Any+z"},
		{"edit_delete", "Any+delete"},
		{"edit_prev_line", "Any+up"},
		{"moveforward", "Any+up"},
		{"edit_next_line", "Any+down"},
		{"moveback", "Any+down"},
		{"edit_end", "Alt+right"},
		{"edit_next_word", "Ctrl+right"},
		{"edit_next_char", "Any+right"},
		{"moveright", "Any+right"},
		{"edit_home", "Alt+left"},
		{"edit_prev_word", "Ctrl+left"},
		{"edit_prev_char", "Any+left"},
		{"moveleft", "Any+left"},
		{"increaseviewradius", "home"},
		{"edit_home", "Any+home"},
		{"decreaseviewradius", "end"},
		{"edit_end", "Any+end"},
		{"moveup", "None"},
		{"movedown", "None"},
		{"showelevation", "C+f1"},
		{"togglestatsgraph", "A+f1"},
		{"showpathtraversability", "C+f2"},
		{"lastmsgpos", "f3"},
		{"showeco", "f4"},
		{"showmetalmap", "None"},
		{"hideinterfaceandcursor", "ctrl+f5"},
		{"NoSound", "None"},
		{"DynamicSky", "None"},
		{"savegame", "Ctrl+Shift+f8"},
		{"luaui showhealthbars", "alt+f9"},
		{"showhealthbars", "alt+f9"},
		{"createvideo", "None"},
		{"viewlobby", "f11"},
		{"luaui tweakgui", "C+f11"},
		{"movefast", "None"},
		{"moveslow", "None"},
		{"movereset", "None"},
		{"movetilt", "Any+ctrl"},
		{"epic_chili_widget_selector_widgetlist_2", "alt+f11"},
		{"screenshot png", "None"},
		{"screenshot jpg", "None"},
		{"settargetcircle", "t"},
		{"resurrect", "t"},
		{"jump", "j"},
		{"field_fac_select", "None"},
		{"build_field_unit", "u"},
		{"select AllMap++_ClearSelection_SelectAll+", "None"},
		{"selectidlecon_all", "C+q"},
		{"select PrevSelection+_Not_RelativeHealth_30+_ClearSelection_SelectAll+", "None"},
		{"select AllMap+_Not_Builder_Not_Building+_ClearSelection_SelectAll+", "None"},
		{"select AllMap+_NameContain_Raptor+_ClearSelection_SelectAll+", "None"},
		{"select PrevSelection+_Idle+_ClearSelection_SelectAll+", "i"},
		{"select AllMap+_Not_Builder_Not_Building_Not_Transport_Aircraft_Radar+_ClearSelection_SelectAll+", "None"},
		{"select AllMap+_Not_Builder_Not_Building_Transport_Aircraft+_ClearSelection_SelectAll+", "None"},
		{"selectidlecon", "q"},
		{"select Visible+_InPrevSel+_ClearSelection_SelectAll+", "None"},
		{"select AllMap+_InPrevSel+_ClearSelection_SelectAll+", "ctrl+z"},
		{"epic_chili_integral_menu_tab_economy", "any+x"},
		{"epic_chili_integral_menu_tab_defence", "any+c"},
		{"epic_chili_integral_menu_tab_special", "any+v"},
		{"epic_chili_integral_menu_tab_factory", "any+b"},
		{"epic_chili_integral_menu_tab_units", "any+n"},
		{"exitwindow", "s+escape"},
		{"crudesubmenu", "f10"},
		{"epic_chili_pro_console_enableconsole", "f8"},
		{"epic_chili_share_menu_v1.22_sharemenu", "tab"},
		{"controlunit", "alt+p"},
		{"epic_auto_group_removefromgroup", "`"},
		{"epic_building_starter_hotkey", "None"},
		{"epic_persistent_build_height_hotkey_toggle", "B"},
		{"epic_persistent_build_height_hotkey_raise", "C"},
		{"epic_persistent_build_height_hotkey_lower", "V"},
		{"epic_lasso_terraform_gui_level_cursor_button_1", "alt+g"},
		{"epic_lasso_terraform_gui_raise_hotkey_1", "alt+v"},
		{"epic_lasso_terraform_gui_raise_hotkey_2", "alt+b"},
		{"epic_lasso_terraform_gui_raise_hotkey_3", "alt+n"},
		{"epic_lasso_terraform_gui_raise_hotkey_4", "alt+h"},
		{"epic_lasso_terraform_gui_raise_hotkey_5", "alt+j"},
		{"epic_lasso_terraform_gui_raise_hotkey_6", "alt+m"},
		{"epic_chili_core_selector_select_factory_1", "alt+Q"},
		{"epic_chili_core_selector_select_factory_2", "alt+W"},
		{"epic_chili_core_selector_select_factory_3", "alt+E"},
		{"epic_chili_core_selector_select_factory_4", "alt+R"},
		{"epic_chili_core_selector_select_factory_5", "alt+T"},
		{"epic_chili_share_menu_v1.24_sharemenu", "f5"},
		{"select AllMap+_IdMatches_gunshipraid_IdMatches_planefighter+_ClearSelection_SelectAll+", "C+w"},
		{"select AllMap+_IdMatches_gunshipskirm_IdMatches_bomberstrike+_ClearSelection_SelectAll+", "C+e"},
		{"select AllMap+_IdMatches_gunshipbomb_IdMatches_bomberriot+_ClearSelection_SelectAll+", "C+r"},
		{"select AllMap+_IdMatches_gunshipassault_IdMatches_bomberprec+_ClearSelection_SelectAll+", "C+t"},
		{"select AllMap+_IdMatches_bomberassault_IdMatches_gunshipheavyskirm+_ClearSelection_SelectAll+", "C+y"},
		{"select AllMap+_IdMatches_gunshipaa_IdMatches_planeheavyfighter_IdMatches_planefighter+_ClearSelection_SelectAll+", "C+d"},
		{"select AllMap+_IdMatches_bomberheavy_IdMatches_gunshipkrow+_ClearSelection_SelectAll+", "C+f"},
		{"select AllMap+_IdMatches_gunshipemp_IdMatches_bomberdisarm+_ClearSelection_SelectAll+", "C+s"},
		{"select AllMap+_IdMatches_subraider_IdMatches_shipaa_IdMatches_shipscout_IdMatches_shiparty_IdMatches_shipassault_IdMatches_shipriot_IdMatches_shipskirm_IdMatches_shiptorpraider+_ClearSelection_SelectAll+", "None"},
		{"viewtaflip", "None"},
		{"sethaven", "home"},
		{"filterfulltransports", "None"},
		{"filteremptytransports", "None"},
		{"epic_auto_group_cleargroups", "end"},
		{"selectfulltransports", "u"},
		{"selectemptytransports", "l"},
		{"select PrevSelection+_Not_RelativeHealth_99+_ClearSelection_SelectAll+", "None"},
		{"epic_icon_zoom_transition_iconmodehotkey", "None"},
		{"select AllMap+_IdMatches_planescout+_ClearSelection_SelectAll+", "C+h"},
		{"armor", "o"},
		{"selectdrones", "Any+d"},
		{"takeoff", "k"},
		{"find_pad", "C+v"},
		{"select PrevSelection++_ClearSelection_SelectPart_50+", "C+x"},
		{"epic_settings/graphics/unit_visibility/icon_zoom_transition_toggle_smooth_icon_zoom", "A+i"},
		{"select AllMap+_IdMatches_planelightscout+_ClearSelection_SelectAll+", "C+g"},
		{"epic_dev_commands_spawn_next_unit", "right"},
		{"epic_dev_commands_spawn_prev_unit", "["},
		{"epic_dev_commands_spawn_set_pos", "]"},
		{"epic_letter_group_icons_(filtered_letters_+_f6/f7_toggle)_enabled", "f7"},
		{"epic_metal_capacity_reached_audio_alert_enablemetalexcessalert", "f9"},
		{"epic_air_reload_filter_(pad-needed_icon_truth)_runnow", "C+c"},
		{"epic_air_rearm_filter_(icon_truth)_runnow", "C+c"},
		{"epic_air_rearm_filter_(icon_truth)_selectallrearmneeded", "A+c"},
		{"epic_air_rearm_filter_runnow", "C+c"},
		{"epic_air_rearm_filter_selectallrearmneeded", "A+c"},
		{"epic_letter_group_icons_(filtered_letters_+_f6/f7_toggle)_drawscreen", "A+f7"},
		{"epic_unit_start_state_veharty_fire_towards_enemy", "None"},
	},
}
